"""Glossário curado pt → es/en/fr do domínio da Corte IDH.

**Para que serve.** Consulta em português não casa com texto em espanhol no FTS:
"saúde" não encontra "salud", "direito" não encontra "derecho". E o acervo é
esmagadoramente espanhol — medido em 18/09/2026, o buscador oficial linka versão
**espanhola** em 597 dos 598 casos contenciosos e em 33 de 33 pareceres, e linka
versão portuguesa em **zero** deles (o PDF em português existe no servidor para
parte do acervo, mas não é linkado; descobre-se sondando). Sem expansão de
consulta, pesquisar em português sobre saúde acharia justamente o que menos
importa — os dois *leading cases* do eixo, Poblete Vilches e Cuscul Pivaral, só
existem em espanhol.

**O que este módulo NÃO é.** Não é tradução do acervo. A via de indexar tradução
automática dos parágrafos foi expressamente rejeitada na spec (§6.1.1): texto
traduzido por máquina, guardado ao lado do texto oficial, acaba citado como se
fosse a fonte. Aqui só se traduzem TERMOS DE BUSCA, que nunca entram na peça.

**Assistência, não garantia.** A expansão é heurística de recuperação. Por isso
quem consulta recebe de volta a lista do que foi expandido — busca que procurou
outra coisa que não o pedido tem de dizê-lo.

**Procedência.** O campo `fonte` de cada linha NÃO é afirmado: é MEDIDO por
`verificar_glossario_cadh.py`, neste mesmo diretório, contra o texto oficial da
Convenção Americana nas quatro línguas. O `fonte` diz quais línguas foram
confirmadas (`CADH:pt,es,en,fr`); o que não se confirmou sai como `curadoria`,
que é ignorância declarada e não defeito. Nada aqui afirma procedência que não
se conferiu.

**O que a medição não prova:** que um termo apareça na CADH não torna correto o
par pt→xx. A medição atesta que o termo é vocabulário da Convenção naquela
língua; a correção do par é curadoria, e está declarada como tal.
"""

from __future__ import annotations

# (pt, es, en, fr) — o `fonte` é preenchido pela medição, nunca escrito à mão.
#
# Ordem temática, espelhando os eixos do mapa temático (§6.3): direitos e
# garantias da CADH, processo, sujeitos vulneráveis, e os eixos materiais
# (saúde, migração, prisão, desaparecimento, indígenas, criança, mulher, LGBTI,
# meio ambiente, acesso à justiça, DESCA/previdência, trabalho).

TERMOS: tuple[tuple[str, str, str, str], ...] = (
    # --- direitos e garantias da Convenção -------------------------------
    ("direito", "derecho", "right", "droit"),
    ("direitos humanos", "derechos humanos", "human rights", "droits de l'homme"),
    ("vida", "vida", "life", "vie"),
    ("integridade pessoal", "integridad personal", "personal integrity",
     "intégrité de la personne"),
    ("liberdade pessoal", "libertad personal", "personal liberty",
     "liberté personnelle"),
    ("dignidade", "dignidad", "dignity", "dignité"),
    ("igualdade", "igualdad", "equality", "égalité"),
    ("não discriminação", "no discriminación", "non-discrimination",
     "non-discrimination"),
    ("discriminação", "discriminación", "discrimination", "discrimination"),
    ("honra", "honra", "honor", "honneur"),
    ("vida privada", "vida privada", "private life", "vie privée"),
    ("liberdade de expressão", "libertad de expresión", "freedom of expression",
     "liberté d'expression"),
    ("liberdade de pensamento", "libertad de pensamiento", "freedom of thought",
     "liberté de pensée"),
    ("liberdade de associação", "libertad de asociación", "freedom of association",
     "liberté d'association"),
    ("propriedade", "propiedad", "property", "propriété"),
    ("personalidade jurídica", "personalidad jurídica", "juridical personality",
     "personnalité juridique"),
    ("nacionalidade", "nacionalidad", "nationality", "nationalité"),
    ("circulação e residência", "circulación y residencia",
     "movement and residence", "circulation et de résidence"),
    ("direitos políticos", "derechos políticos", "political rights",
     "droits politiques"),
    ("proteção da família", "protección a la familia", "protection of the family",
     "protection de la famille"),
    ("proteção judicial", "protección judicial", "judicial protection",
     "protection judiciaire"),
    ("garantias judiciais", "garantías judiciales", "judicial guarantees",
     "garanties judiciaires"),
    ("obrigação de respeitar", "obligación de respetar",
     "obligation to respect", "obligation de respecter"),
    ("dever de garantir", "deber de garantizar", "duty to ensure",
     "devoir de garantir"),
    ("escravidão", "esclavitud", "slavery", "esclavage"),
    ("servidão", "servidumbre", "servitude", "servitude"),
    ("trabalho forçado", "trabajo forzoso", "forced labor", "travail forcé"),
    ("tortura", "tortura", "torture", "torture"),
    ("tratamento cruel", "trato cruel", "cruel treatment", "traitement cruel"),
    ("tratamento degradante", "trato degradante", "degrading treatment",
     "traitement dégradant"),
    ("pena de morte", "pena de muerte", "death penalty", "peine de mort"),
    ("retroatividade", "retroactividad", "retroactivity", "rétroactivité"),
    ("presunção de inocência", "presunción de inocencia",
     "presumption of innocence", "présomption d'innocence"),
    ("indenização", "indemnización", "compensation", "indemnisation"),
    ("desenvolvimento progressivo", "desarrollo progresivo",
     "progressive development", "développement progressif"),

    # --- processo e reparação --------------------------------------------
    ("sentença", "sentencia", "judgment", "arrêt"),
    ("mérito", "fondo", "merits", "fond"),
    ("exceções preliminares", "excepciones preliminares",
     "preliminary objections", "exceptions préliminaires"),
    ("reparações", "reparaciones", "reparations", "réparations"),
    ("custas", "costas", "costs", "dépens"),
    ("medidas provisórias", "medidas provisionales", "provisional measures",
     "mesures provisoires"),
    ("supervisão de cumprimento", "supervisión de cumplimiento",
     "monitoring compliance", "surveillance de l'exécution"),
    ("parecer consultivo", "opinión consultiva", "advisory opinion",
     "avis consultatif"),
    ("interpretação da sentença", "interpretación de la sentencia",
     "interpretation of the judgment", "interprétation de l'arrêt"),
    ("esgotamento dos recursos internos", "agotamiento de los recursos internos",
     "exhaustion of domestic remedies", "épuisement des recours internes"),
    ("recurso efetivo", "recurso efectivo", "effective remedy",
     "recours effectif"),
    ("devido processo", "debido proceso", "due process", "procès équitable"),
    ("prazo razoável", "plazo razonable", "reasonable time", "délai raisonnable"),
    ("juiz natural", "juez natural", "competent tribunal", "juge naturel"),
    ("imparcialidade", "imparcialidad", "impartiality", "impartialité"),
    ("ampla defesa", "derecho de defensa", "right to defense",
     "droit de la défense"),
    ("duplo grau", "doble instancia", "right to appeal", "double instance"),
    ("coisa julgada", "cosa juzgada", "res judicata", "chose jugée"),
    ("controle de convencionalidade", "control de convencionalidad",
     "conventionality control", "contrôle de conventionnalité"),
    ("responsabilidade internacional", "responsabilidad internacional",
     "international responsibility", "responsabilité internationale"),
    ("restituição", "restitución", "restitution", "restitution"),
    ("satisfação", "satisfacción", "satisfaction", "satisfaction"),
    ("dano material", "daño material", "pecuniary damage", "dommage matériel"),
    ("dano imaterial", "daño inmaterial", "non-pecuniary damage",
     "dommage immatériel"),
    ("garantia de não repetição", "garantía de no repetición",
     "guarantee of non-repetition", "garantie de non-répétition"),
    ("dever de investigar", "deber de investigar", "duty to investigate",
     "devoir d'enquêter"),
    ("impunidade", "impunidad", "impunity", "impunité"),
    ("anistia", "amnistía", "amnesty", "amnistie"),
    ("prescrição", "prescripción", "statute of limitations", "prescription"),
    ("vítima", "víctima", "victim", "victime"),
    ("familiares", "familiares", "next of kin", "proches"),
    ("prova", "prueba", "evidence", "preuve"),
    ("ônus da prova", "carga de la prueba", "burden of proof",
     "charge de la preuve"),
    ("presunção", "presunción", "presumption", "présomption"),

    # --- vulnerabilidade e grupos ---------------------------------------
    ("vulnerabilidade", "vulnerabilidad", "vulnerability", "vulnérabilité"),
    ("situação de vulnerabilidade", "situación de vulnerabilidad",
     "situation of vulnerability", "situation de vulnérabilité"),
    ("grupo em situação de risco", "grupo en situación de riesgo",
     "at-risk group", "groupe à risque"),
    ("pobreza", "pobreza", "poverty", "pauvreté"),
    ("pessoa com deficiência", "persona con discapacidad",
     "person with disability", "personne handicapée"),
    ("deficiência", "discapacidad", "disability", "handicap"),
    ("pessoa idosa", "persona mayor", "older person", "personne âgée"),
    ("criança", "niño", "child", "enfant"),
    ("adolescente", "adolescente", "adolescent", "adolescent"),
    ("interesse superior da criança", "interés superior del niño",
     "best interests of the child", "intérêt supérieur de l'enfant"),
    ("mulher", "mujer", "woman", "femme"),
    ("violência contra a mulher", "violencia contra la mujer",
     "violence against women", "violence à l'égard des femmes"),
    ("violência de gênero", "violencia de género", "gender-based violence",
     "violence fondée sur le genre"),
    ("gênero", "género", "gender", "genre"),
    ("identidade de gênero", "identidad de género", "gender identity",
     "identité de genre"),
    ("orientação sexual", "orientación sexual", "sexual orientation",
     "orientation sexuelle"),
    ("povos indígenas", "pueblos indígenas", "indigenous peoples",
     "peuples autochtones"),
    ("comunidade indígena", "comunidad indígena", "indigenous community",
     "communauté autochtone"),
    ("território tradicional", "territorio tradicional",
     "traditional territory", "territoire traditionnel"),
    ("propriedade coletiva", "propiedad colectiva", "collective property",
     "propriété collective"),
    ("consulta prévia", "consulta previa", "prior consultation",
     "consultation préalable"),
    ("consentimento livre e informado", "consentimiento libre e informado",
     "free and informed consent", "consentement libre et éclairé"),
    ("afrodescendente", "afrodescendiente", "afro-descendant",
     "afro-descendant"),
    ("quilombola", "quilombola", "quilombola", "quilombola"),
    ("camponês", "campesino", "peasant", "paysan"),

    # --- saúde -----------------------------------------------------------
    ("saúde", "salud", "health", "santé"),
    ("direito à saúde", "derecho a la salud", "right to health",
     "droit à la santé"),
    ("atenção médica", "atención médica", "medical care", "soins médicaux"),
    ("tratamento médico", "tratamiento médico", "medical treatment",
     "traitement médical"),
    ("medicamento", "medicamento", "medicine", "médicament"),
    ("hospital", "hospital", "hospital", "hôpital"),
    ("saúde mental", "salud mental", "mental health", "santé mentale"),
    ("internação psiquiátrica", "internación psiquiátrica",
     "psychiatric commitment", "hospitalisation psychiatrique"),
    ("consentimento informado", "consentimiento informado",
     "informed consent", "consentement éclairé"),
    ("saúde sexual e reprodutiva", "salud sexual y reproductiva",
     "sexual and reproductive health", "santé sexuelle et reproductive"),
    ("negligência médica", "negligencia médica", "medical negligence",
     "négligence médicale"),
    ("seguridade social", "seguridad social", "social security",
     "sécurité sociale"),
    ("aposentadoria", "jubilación", "pension", "retraite"),
    ("pensão", "pensión", "pension", "pension"),

    # --- migração e refúgio ----------------------------------------------
    ("migrante", "migrante", "migrant", "migrant"),
    ("migração", "migración", "migration", "migration"),
    ("pessoa em situação migratória irregular",
     "persona en situación migratoria irregular",
     "migrant in an irregular situation",
     "migrant en situation irrégulière"),
    ("estrangeiro", "extranjero", "alien", "étranger"),
    ("expulsão", "expulsión", "expulsion", "expulsion"),
    ("deportação", "deportación", "deportation", "expulsion"),
    ("expulsão coletiva", "expulsión colectiva", "collective expulsion",
     "expulsion collective"),
    ("refugiado", "refugiado", "refugee", "réfugié"),
    ("asilo", "asilo", "asylum", "asile"),
    ("não devolução", "no devolución", "non-refoulement", "non-refoulement"),
    ("apátrida", "apátrida", "stateless person", "apatride"),
    ("assistência consular", "asistencia consular", "consular assistance",
     "assistance consulaire"),
    ("fronteira", "frontera", "border", "frontière"),

    # --- privação de liberdade -------------------------------------------
    ("privação de liberdade", "privación de libertad",
     "deprivation of liberty", "privation de liberté"),
    ("pessoa privada de liberdade", "persona privada de libertad",
     "person deprived of liberty", "personne privée de liberté"),
    ("prisão", "prisión", "prison", "prison"),
    ("detenção arbitrária", "detención arbitraria", "arbitrary detention",
     "détention arbitraire"),
    ("prisão preventiva", "prisión preventiva", "pretrial detention",
     "détention provisoire"),
    ("condições de detenção", "condiciones de detención",
     "conditions of detention", "conditions de détention"),
    ("superlotação", "hacinamiento", "overcrowding", "surpopulation"),
    ("incomunicabilidade", "incomunicación", "incommunicado detention",
     "mise au secret"),
    ("habeas corpus", "hábeas corpus", "habeas corpus", "habeas corpus"),
    ("execução extrajudicial", "ejecución extrajudicial",
     "extrajudicial execution", "exécution extrajudiciaire"),
    ("uso da força", "uso de la fuerza", "use of force", "usage de la force"),

    # --- desaparecimento e justiça de transição --------------------------
    ("desaparecimento forçado", "desaparición forzada",
     "forced disappearance", "disparition forcée"),
    ("desaparecimento", "desaparición", "disappearance", "disparition"),
    ("ditadura", "dictadura", "dictatorship", "dictature"),
    ("crime contra a humanidade", "crimen de lesa humanidad",
     "crime against humanity", "crime contre l'humanité"),
    ("massacre", "masacre", "massacre", "massacre"),
    ("verdade", "verdad", "truth", "vérité"),
    ("direito à verdade", "derecho a la verdad", "right to the truth",
     "droit à la vérité"),
    ("memória", "memoria", "memory", "mémoire"),
    ("jurisdição militar", "jurisdicción militar", "military jurisdiction",
     "juridiction militaire"),

    # --- trabalho, meio ambiente, DESCA ---------------------------------
    ("trabalho escravo", "trabajo esclavo", "slave labor", "travail esclave"),
    ("tráfico de pessoas", "trata de personas", "human trafficking",
     "traite des personnes"),
    ("condições de trabalho", "condiciones de trabajo",
     "working conditions", "conditions de travail"),
    ("liberdade sindical", "libertad sindical", "freedom of association",
     "liberté syndicale"),
    ("meio ambiente", "medio ambiente", "environment", "environnement"),
    ("meio ambiente sadio", "medio ambiente sano", "healthy environment",
     "environnement sain"),
    ("água", "agua", "water", "eau"),
    ("alimentação", "alimentación", "food", "alimentation"),
    ("moradia", "vivienda", "housing", "logement"),
    ("educação", "educación", "education", "éducation"),
    ("direitos econômicos sociais e culturais",
     "derechos económicos sociales y culturales",
     "economic social and cultural rights",
     "droits économiques sociaux et culturels"),
    ("empresa", "empresa", "business", "entreprise"),

    # --- acesso à justiça e defensoria ----------------------------------
    ("acesso à justiça", "acceso a la justicia", "access to justice",
     "accès à la justice"),
    ("assistência jurídica gratuita", "asistencia jurídica gratuita",
     "free legal aid", "aide juridictionnelle gratuite"),
    ("defensor público", "defensor público", "public defender",
     "défenseur public"),
    ("defensoria pública", "defensoría pública", "public defender's office",
     "défense publique"),
    ("intérprete", "intérprete", "interpreter", "interprète"),
    ("assistência letrada", "asistencia letrada", "legal assistance",
     "assistance juridique"),
    ("hipossuficiência", "carencia de recursos", "lack of means",
     "absence de ressources"),
    ("gratuidade", "gratuidad", "free of charge", "gratuité"),
)
